### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by aykutsimseks** [NaturalHistoryMuseum/ckanext-gallery#1]
Hi,

Is there a sample CKAN instance running the extension. I went through http://data.nhm.ac.uk/ , but couldn't exactly find where it is. Will be great if you could add link to an example in README.md.

**Comment by benscott** [comment]
You can see this working at: http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?view_id=6ba121d1-da26-4ee1-81fa-7da11e68f68e

I have updated readme too with this info - thanks for pointing this out.
