### ISSUE TITLE
Installation and configuration documentation

### ISSUE THREAD

**Issue by trendspotter** [NaturalHistoryMuseum/ckanext-gallery#12]
How does one properly install and configure this extension? The readme doesn't provide any details. Having mainly sysadmin background and not knowing all the technological shortcuts cool kids use today, it took me considerable amount of time to figure out how the extension should probably be installed, but I still can't seem to get it working.

So far I found out that the extension requires NodeJS runtime (which version?) and figured out these steps to install:
```
pip install -e 'git+https://github.com/NaturalHistoryMuseum/ckanext-gallery#egg=ckanext_gallery'
cd ${CKAN_HOME}/src/ckanext-gallery
npm install bower
bower install
```
Then activate the extension by adding `ckan.plugins = ... gallery`.

What else I'm missing? Would be nice to add the steps into README.md too.

**Comment by alycejenni** [comment]
sorry this took so long, but the README now has a decent amount of documentation - let us know if there's anything missing!
