### ISSUE TITLE
ckan.module is not a function

### ISSUE THREAD

**Issue by grptx** [NaturalHistoryMuseum/ckanext-gallery#43]
After installing the extension and configuring the view I get the following error in the console log
```
1a378078b007463ee038292c98e5fcc9_gallery.js:5 Uncaught TypeError: ckan.module is not a function
    at 1a378078b007463ee038292c98e5fcc9_gallery.js:5:6
```

![image](https://github.com/NaturalHistoryMuseum/ckanext-gallery/assets/6595328/12ff289e-7e41-42be-99a2-bd0282134c6b)

How can I solve this?

 - CKAN version: 2.10.0
 - Docker compose

**Comment by jrdh** [comment]
Hi @grptx - I have proposed a fix that I have not tested yet here https://github.com/NaturalHistoryMuseum/ckanext-gallery/pull/44. I will see if I can test it today/tomorrow, or, if you have the ability to test it before then and let me know if it fixes your problem, that would be great too!

**Comment by grptx** [comment]
it works perfectly! thank you so much

**Comment by jrdh** [comment]
Great! Thanks for checking that, I'll get it merged and we'll do a release next week to properly get it out.
